### ISSUE TITLE
Update the cbd.xml with the address of the parking lots

### ISSUE THREAD

**Issue by wcomnisky** [JayJanarthanan/AucklandMotoParking#3]
The current cbd.xml from the initial commit is empty.

@JayJanarthanan could you provide the file with the addresses please?

Thanks

**Comment by JayJanarthanan** [comment]
This has been fixed. The XML file is hosted on Azure and available here: https://appsettings.blob.core.windows.net/storage/cbd.xml

**Comment by wcomnisky** [comment]
:cool: :thumbsup:
